#' ---
#' title: "BDAT602 Project -- Task 2: Customer Risk Segmentation via Cluster Analysis"
#' subtitle: "Data Generation, Variable Selection, Cleaning, Preprocessing, and Clustering"
#' author: "BDAT602 Group Project"
#' date: "`r format(Sys.Date(), '%d %B %Y')`"
#' output:
#'   html_document:
#'     toc: true
#'     toc_depth: 3
#'     toc_float: true
#'     number_sections: true
#'     theme: flatly
#' ---
#' 
## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                       fig.width = 7.5, fig.height = 5, dpi = 150)
options(scipen = 999)

#' 
#' # Data Generation
#' 
#' The simulated retail banking dataset (~100,000 customers) is generated by the function below,
#' supplied for the project. It produces demographic, product-holding, transaction, credit-risk,
#' and engagement variables, together with a set of intentionally embedded data-quality issues
#' (missing values, outliers/entry errors, inconsistent labels, and duplicate rows) that are
#' identified and corrected in Section 3.
#' 
## ----data-generation-function-------------------------------------------------
suppressMessages({
  library(dplyr)
  library(lubridate)
})

simulate_bdat602_project <- function(n = 100000, seed = 602) {
  set.seed(seed)

  # -- SECTION 1: IDENTIFIERS ---------------------------------------------
  customer_id   <- 1:n
  branch_id     <- sample(1:300, n, replace = TRUE)
  relationship_manager_id <- sample(1:800, n, replace = TRUE)
  account_open_date <- as.Date("2024-12-31") -
    days(round(rlnorm(n, meanlog = 6.5, sdlog = 1.0)))

  # -- SECTION 2: DEMOGRAPHICS --------------------------------------------
  age <- pmax(18, pmin(85, round(rnorm(n, mean = 41, sd = 13))))

  gender <- sample(c("Male", "Female", "Other"), n, replace = TRUE,
                    prob = c(0.48, 0.50, 0.02))

  region <- sample(
    c("Greater Accra", "Ashanti", "Western", "Eastern",
      "Northern", "Volta", "Central", "Bono"),
    n, replace = TRUE,
    prob = c(0.30, 0.20, 0.12, 0.10, 0.10, 0.08, 0.06, 0.04)
  )

  education <- sample(
    c("None", "Primary", "Secondary", "Tertiary", "Postgraduate"),
    n, replace = TRUE,
    prob = c(0.04, 0.12, 0.32, 0.38, 0.14)
  )

  employment_status <- sample(
    c("Salaried", "Self-Employed", "Business Owner", "Student", "Unemployed", "Retired"),
    n, replace = TRUE,
    prob = c(0.42, 0.20, 0.13, 0.08, 0.07, 0.10)
  )

  marital_status <- sample(
    c("Single", "Married", "Divorced", "Widowed"),
    n, replace = TRUE,
    prob = c(0.42, 0.45, 0.08, 0.05)
  )

  dependents <- pmax(0, round(rpois(n, lambda = ifelse(
    marital_status == "Married", 2.0, 0.5
  ))))

  base_income <- case_when(
    education == "None"          ~  600,
    education == "Primary"       ~ 1000,
    education == "Secondary"     ~ 2200,
    education == "Tertiary"      ~ 4500,
    education == "Postgraduate"  ~ 8000,
    TRUE ~ 2200
  )

  monthly_income <- round(
    base_income *
      case_when(
        employment_status == "Salaried"       ~ 1.00,
        employment_status == "Self-Employed"  ~ 1.15,
        employment_status == "Business Owner" ~ 1.45,
        employment_status == "Student"        ~ 0.25,
        employment_status == "Unemployed"     ~ 0.15,
        employment_status == "Retired"        ~ 0.65,
        TRUE ~ 1.00
      ) *
      ifelse(region %in% c("Greater Accra", "Ashanti"), 1.30, 1.00) *
      rlnorm(n, meanlog = 0, sdlog = 0.40),
    2
  )

  # -- SECTION 3: ACCOUNT & PRODUCT HOLDINGS ------------------------------
  account_type <- sample(
    c("Basic", "Standard", "Premium", "Private Banking"),
    n, replace = TRUE,
    prob = c(0.40, 0.35, 0.18, 0.07)
  )

  has_savings_account <- rbinom(n, 1, prob = 0.95)

  has_current_account <- rbinom(n, 1, prob = plogis(
    -1.0 + 0.9 * (account_type %in% c("Standard","Premium","Private Banking")) +
      0.3 * (employment_status %in% c("Salaried","Business Owner"))
  ))

  has_fixed_deposit <- rbinom(n, 1, prob = plogis(
    -2.0 + 0.7 * (account_type %in% c("Premium","Private Banking")) +
      0.5 * (log1p(monthly_income) > 8)
  ))

  has_credit_card <- rbinom(n, 1, prob = plogis(
    -2.2 + 1.0 * (account_type %in% c("Standard","Premium","Private Banking")) +
      0.4 * (employment_status == "Salaried") +
      0.3 * (age > 28)
  ))

  has_personal_loan <- rbinom(n, 1, prob = plogis(
    -2.0 + 0.5 * (employment_status %in% c("Salaried","Business Owner")) +
      0.3 * (dependents > 1) -
      0.4 * (account_type == "Private Banking")
  ))

  has_mortgage <- rbinom(n, 1, prob = plogis(
    -3.5 + 0.8 * (age > 30 & age < 60) +
      0.6 * (log1p(monthly_income) > 8.5) +
      0.5 * (marital_status == "Married")
  ))

  has_investment_account <- rbinom(n, 1, prob = plogis(
    -2.5 + 1.0 * (account_type %in% c("Premium","Private Banking")) +
      0.5 * (education %in% c("Tertiary","Postgraduate"))
  ))

  has_insurance_product <- rbinom(n, 1, prob = plogis(
    -1.8 + 0.5 * (has_mortgage == 1) +
      0.4 * (dependents > 0) +
      0.3 * (account_type != "Basic")
  ))

  has_mobile_banking <- rbinom(n, 1, prob = plogis(
    -0.5 + 0.6 * (age < 45) +
      0.4 * (education %in% c("Tertiary","Postgraduate")) +
      0.3 * (region %in% c("Greater Accra","Ashanti"))
  ))

  has_overdraft_facility <- rbinom(n, 1, prob = plogis(
    -2.5 + 0.7 * (account_type %in% c("Premium","Private Banking")) +
      0.4 * (employment_status == "Business Owner")
  ))

  # -- SECTION 4: BALANCES AND TRANSACTIONS -------------------------------
  savings_balance <- round(
    pmax(0, monthly_income) *
      runif(n, 0.5, 8) *
      case_when(
        account_type == "Basic"           ~ 0.4,
        account_type == "Standard"        ~ 1.0,
        account_type == "Premium"         ~ 2.5,
        account_type == "Private Banking" ~ 6.0,
        TRUE ~ 1.0
      ) *
      rlnorm(n, 0, 0.6),
    2
  )

  current_balance <- ifelse(
    has_current_account == 1,
    round(monthly_income * runif(n, 0.2, 2.0) * rlnorm(n, 0, 0.5), 2),
    0
  )

  avg_monthly_transactions <- rpois(n, lambda = pmax(1,
                                                      3 + 0.002 * monthly_income +
                                                        5 * has_mobile_banking +
                                                        3 * (account_type %in% c("Premium","Private Banking"))
  ))

  avg_transaction_value <- round(
    pmax(5, monthly_income / pmax(1, avg_monthly_transactions) *
           rlnorm(n, 0, 0.4)),
    2
  )

  atm_withdrawals_monthly <- rpois(n, lambda = pmax(0.2,
                                                     4 - 1.5 * has_mobile_banking + 0.5 * (age > 50)
  ))

  online_transactions_monthly <- rpois(n, lambda = pmax(0,
                                                         2 + 8 * has_mobile_banking +
                                                           0.001 * monthly_income -
                                                           0.05 * age
  ))

  international_transactions_yearly <- rpois(n, lambda = pmax(0,
                                                               0.2 + 0.0008 * monthly_income +
                                                                 1.5 * (account_type %in% c("Premium","Private Banking"))
  ))

  overdraft_usage_yearly <- ifelse(
    has_overdraft_facility == 1,
    rpois(n, lambda = pmax(0, 2 + 0.3 * (employment_status=="Business Owner"))),
    0
  )

  # -- SECTION 5: CREDIT & RISK PROFILE ------------------------------------
  credit_score_base <- 650 +
    1.5 * (log1p(monthly_income) - 7) * 20 +
    0.3 * age -
    30 * has_overdraft_facility -
    15 * overdraft_usage_yearly +
    rnorm(n, 0, 40)

  credit_score <- round(pmax(300, pmin(850, credit_score_base)))

  num_active_loans <- has_personal_loan + has_mortgage +
    rbinom(n, 1, prob = plogis(-2 + 0.3*(employment_status=="Business Owner")))

  total_outstanding_debt <- round(
    pmax(0,
         has_personal_loan * runif(n, 500, 15000) +
           has_mortgage      * runif(n, 20000, 250000) +
           has_overdraft_facility * overdraft_usage_yearly * runif(n, 100, 2000)
    ),
    2
  )

  debt_to_income_ratio <- round(
    total_outstanding_debt / pmax(1, monthly_income * 12),
    3
  )

  num_missed_payments <- rpois(n, lambda = pmax(0,
                                                0.3 + 0.02 * debt_to_income_ratio * 10 -
                                                  0.005 * (credit_score - 600)
  ))

  default_prob <- plogis(
    -3.0 +
      0.04 * num_missed_payments +
      1.5  * (debt_to_income_ratio > 0.5) -
      0.01 * (credit_score - 600) +
      0.3  * (employment_status %in% c("Unemployed","Student"))
  )
  loan_default_flag <- rbinom(n, 1, prob = pmin(default_prob, 0.6))

  # -- SECTION 6: CUSTOMER BEHAVIOUR & ENGAGEMENT --------------------------
  tenure_years <- round(as.numeric(as.Date("2024-12-31") - account_open_date) / 365.25, 2)

  satisfaction_score <- pmin(10, pmax(1, round(
    7.0 -
      0.5 * num_missed_payments +
      0.3 * has_mobile_banking +
      0.2 * (account_type %in% c("Premium","Private Banking")) +
      rnorm(n, 0, 1.5)
  )))

  branch_visits_yearly <- rpois(n, lambda = pmax(0,
                                                 6 - 4 * has_mobile_banking + 0.05 * age
  ))

  num_complaints <- rpois(n, lambda = pmax(0,
                                           0.2 + 0.3 * num_missed_payments +
                                             0.4 * (satisfaction_score < 4)
  ))

  churn_prob <- plogis(
    -2.0 -
      0.3 * (satisfaction_score - 5) +
      0.2 * num_complaints -
      0.3 * has_mobile_banking -
      0.05 * tenure_years +
      0.2 * (account_type == "Basic")
  )
  churned <- rbinom(n, 1, prob = pmin(churn_prob, 0.7))

  # -- SECTION 7: FREE-TEXT FEEDBACK ---------------------------------------
  feedback_templates <- c(
    "The mobile app keeps crashing whenever I try to make a transfer.",
    "My loan application took far too long to be approved.",
    "Customer service at the branch was excellent and very helpful.",
    "I was charged a fee I did not understand on my statement.",
    "The new online banking interface is confusing to navigate.",
    "Staff at the branch were rude and unprofessional during my visit.",
    "I appreciate the quick response when I reported a lost card.",
    "Interest rates on savings accounts are too low compared to competitors.",
    "The ATM near my home is frequently out of cash.",
    "Setting up the fixed deposit was smooth and well explained.",
    "I have been waiting for a refund on a failed transaction for weeks.",
    "The credit card application process was straightforward and fast.",
    "There is no clear information about overdraft charges.",
    "I love the new budgeting feature in the mobile app.",
    "My relationship manager rarely responds to my emails."
  )

  customer_feedback <- sample(feedback_templates, n, replace = TRUE)
  customer_feedback[sample(1:n, size = round(n * 0.15))] <- NA_character_

  # -- SECTION 8: INTENTIONAL DATA QUALITY ISSUES --------------------------
  monthly_income[sample(1:n, size = round(n * 0.06))] <- NA_real_
  credit_score[sample(1:n, size = round(n * 0.04))] <- NA_real_
  dependents[sample(1:n, size = round(n * 0.03))] <- NA_integer_
  satisfaction_score[sample(1:n, size = round(n * 0.05))] <- NA_real_

  age[sample(1:n, size = round(n * 0.001))] <- sample(c(1, 5, 130, 150), round(n*0.001), replace = TRUE)
  monthly_income[sample(1:n, size = round(n * 0.001))] <- sample(c(0, -500, 5000000), round(n*0.001), replace = TRUE)
  savings_balance[sample(1:n, size = round(n * 0.0015))] <-
    savings_balance[sample(1:n, size = round(n * 0.0015))] * 1000
  debt_to_income_ratio[sample(1:n, size = round(n * 0.0008))] <- -abs(
    debt_to_income_ratio[sample(1:n, size = round(n * 0.0008))]
  )

  gender_messy <- gender
  messy_idx <- sample(1:n, size = round(n * 0.02))
  gender_messy[messy_idx] <- case_when(
    gender_messy[messy_idx] == "Male"   ~ sample(c("male","MALE","M"), length(messy_idx), replace=TRUE),
    gender_messy[messy_idx] == "Female" ~ sample(c("female","FEMALE","F"), length(messy_idx), replace=TRUE),
    TRUE ~ gender_messy[messy_idx]
  )

  region_messy <- region
  messy_idx2 <- sample(1:n, size = round(n * 0.015))
  region_messy[messy_idx2] <- trimws(paste0(" ", region_messy[messy_idx2], "  "))

  bad_date_idx <- sample(1:n, size = round(n * 0.0005))
  account_open_date[bad_date_idx] <- as.Date("2026-01-01") + days(sample(1:300, length(bad_date_idx), replace=TRUE))

  # -- ASSEMBLE FINAL DATA FRAME --------------------------------------------
  df <- data.frame(
    customer_id, branch_id, relationship_manager_id, account_open_date,
    age, gender = gender_messy, region = region_messy, education,
    employment_status, marital_status, dependents, monthly_income,
    account_type, has_savings_account, has_current_account, has_fixed_deposit,
    has_credit_card, has_personal_loan, has_mortgage, has_investment_account,
    has_insurance_product, has_mobile_banking, has_overdraft_facility,
    savings_balance, current_balance, avg_monthly_transactions,
    avg_transaction_value, atm_withdrawals_monthly, online_transactions_monthly,
    international_transactions_yearly, overdraft_usage_yearly,
    credit_score, num_active_loans, total_outstanding_debt,
    debt_to_income_ratio, num_missed_payments, loan_default_flag,
    tenure_years, satisfaction_score, branch_visits_yearly, num_complaints,
    churned, customer_feedback,
    stringsAsFactors = FALSE
  )

  dup_idx <- sample(1:nrow(df), size = round(nrow(df) * 0.003))
  df <- bind_rows(df, df[dup_idx, ])

  return(df)
}

df_raw <- simulate_bdat602_project(n = 100000, seed = 602)
cat("Generated dataset:", nrow(df_raw), "rows x", ncol(df_raw), "columns\n")

#' 
#' # Variable Selection
#' 
#' **(a) Segmentation problem.** This task investigates how retail banking customers can be
#' grouped into distinct **risk profiles** -- e.g. low-risk, financially stable customers versus
#' high-risk, over-leveraged or delinquency-prone customers -- so the bank can differentiate credit
#' exposure management, pricing, and collections strategies across segments.
#' 
#' **(b) Selected variables.** The cluster analysis draws on `monthly_income`, `savings_balance`,
#' `current_balance`, `credit_score`, `num_active_loans`, `total_outstanding_debt`,
#' `debt_to_income_ratio`, `num_missed_payments`, and `overdraft_usage_yearly`. Jointly these
#' capture three complementary dimensions of risk: (i) **repayment capacity** (income, savings and
#' current balances as buffers against shocks), (ii) **leverage** (outstanding debt, DTI, number of
#' active loans), and (iii) **repayment behaviour** (missed payments, overdraft usage, credit score
#' as a composite behavioural summary).
#' 
#' **(c) Excluded alternatives.** Demographic fields (age, gender, education, region, marital
#' status) were excluded as they are not direct financial-risk indicators and raise
#' proxy-discrimination concerns. Identifiers (`customer_id`, `branch_id`,
#' `relationship_manager_id`) were dropped as meaningless for clustering. Engagement/service
#' variables (`satisfaction_score`, `branch_visits_yearly`, `num_complaints`, `churned`,
#' `has_mobile_banking`) were excluded as they reflect service experience rather than credit risk.
#' `loan_default_flag` was excluded because it is the eventual supervised target and its inclusion
#' would leak the outcome into an unsupervised risk-clustering exercise.
#' 
#' **(d) Correlation-based exclusions.** `has_personal_loan` and `has_mortgage` were dropped
#' because they are already summarised in `num_active_loans`. `avg_transaction_value` and
#' `avg_monthly_transactions` were excluded as they correlate strongly with `monthly_income` and
#' mainly reflect channel activity rather than risk.
#' 
## ----select-vars--------------------------------------------------------------
clust_vars <- c("customer_id","monthly_income","savings_balance","current_balance",
                 "credit_score","num_active_loans","total_outstanding_debt",
                 "debt_to_income_ratio","num_missed_payments","overdraft_usage_yearly")

df <- df_raw

#' 
#' # Data Cleaning
#' 
#' ## Inspect data quality issues
#' 
## ----inspect-issues-----------------------------------------------------------
cat("=== Missing values ===\n")
print(sapply(df[clust_vars], function(x) sum(is.na(x))))

cat("\n=== Duplicate rows ===\n")
cat("Total rows:", nrow(df), " Unique customer_id:", length(unique(df$customer_id)), "\n")
cat("Fully duplicated rows:", sum(duplicated(df)), "\n")

cat("\n=== Implausible values ===\n")
cat("monthly_income <= 0 or > 30,000:",
    sum(df$monthly_income <= 0 | df$monthly_income > 30000, na.rm = TRUE), "\n")
cat("debt_to_income_ratio < 0:", sum(df$debt_to_income_ratio < 0, na.rm = TRUE), "\n")
cat("savings_balance > 99.5th percentile cap candidates:",
    sum(df$savings_balance > quantile(df$savings_balance, 0.995, na.rm = TRUE)), "\n")

#' 
#' ## Issue 1 -- Exact duplicate records
#' 
#' 300 fully duplicated rows (0.3%) are present, from a data-integration duplication step.
#' **Fix:** removed via `distinct()`. Deduplication is unambiguous here since the rows are
#' byte-for-byte identical, so removal loses no information and introduces no bias.
#' 
## ----clean-duplicates---------------------------------------------------------
n_dup <- sum(duplicated(df))
df <- df %>% distinct()
cat(sprintf("Removed %d exact duplicate rows -> %d rows remain\n", n_dup, nrow(df)))

#' 
#' ## Issue 2 -- Implausible / impossible values (data entry errors)
#' 
#' - `monthly_income`: non-positive values and an implausible extreme spike (up to 5,000,000).
#'   Recoded to `NA` (handled with the genuine missing values in Issue 3).
#' - `debt_to_income_ratio`: negative ratios are mathematically impossible -- corrected via
#'   `abs()`, which exactly reverses the sign-flip entry error.
#' - `savings_balance`: "extra zero" entry errors (~1000x inflation) -- winsorised (capped) at the
#'   99.5th percentile rather than deleted, preserving the record while preventing a handful of
#'   rows from dominating distance-based clustering.
#' 
## ----clean-implausible--------------------------------------------------------
n_income_bad <- sum(df$monthly_income <= 0 | df$monthly_income > 30000, na.rm = TRUE)
df$monthly_income[df$monthly_income <= 0] <- NA
df$monthly_income[df$monthly_income > 30000] <- NA
cat(sprintf("Recoded %d implausible monthly_income values to NA\n", n_income_bad))

n_dti_neg <- sum(df$debt_to_income_ratio < 0, na.rm = TRUE)
df$debt_to_income_ratio <- abs(df$debt_to_income_ratio)
cat(sprintf("Corrected %d negative debt_to_income_ratio values via abs()\n", n_dti_neg))

sb_cap <- as.numeric(quantile(df$savings_balance, 0.995, na.rm = TRUE))
n_sb_out <- sum(df$savings_balance > sb_cap, na.rm = TRUE)
df$savings_balance <- pmin(df$savings_balance, sb_cap)
cat(sprintf("Winsorised %d extreme savings_balance values to the 99.5%% cap (%.0f)\n",
            n_sb_out, sb_cap))

#' 
#' ## Issue 3 -- Missing values
#' 
#' `monthly_income` (~6%) and `credit_score` (~4%) contain missing values. **Fix:** median
#' imputation, with a `*_was_missing` flag retained for each. Listwise deletion would discard
#' ~10% of customers and could bias segments if missingness relates to customer type; mean
#' imputation was rejected because both variables are heavily right-skewed, so the median better
#' represents a "typical" customer. The missingness flags preserve the information that a value
#' was imputed.
#' 
## ----clean-missing------------------------------------------------------------
n_miss_income <- sum(is.na(df$monthly_income))
n_miss_credit <- sum(is.na(df$credit_score))

df$income_was_missing <- as.integer(is.na(df$monthly_income))
df$credit_was_missing <- as.integer(is.na(df$credit_score))

df$monthly_income[is.na(df$monthly_income)] <- median(df$monthly_income, na.rm = TRUE)
df$credit_score[is.na(df$credit_score)]     <- median(df$credit_score, na.rm = TRUE)

cat(sprintf("Median-imputed %d missing monthly_income and %d missing credit_score values\n",
            n_miss_income, n_miss_credit))

cat("\nRemaining NAs in clustering variables:\n")
print(sapply(df[clust_vars], function(x) sum(is.na(x))))

#' 
#' # Preprocessing
#' 
#' Skewness is assessed empirically to choose an appropriate transform/scaling method per variable.
#' 
## ----skew-function------------------------------------------------------------
skew <- function(x){ m <- mean(x); s <- sd(x); mean((x - m)^3) / s^3 }

#' 
#' ## Group A -- highly right-skewed monetary variables: log1p + Z-score
#' 
## ----preprocess-log-----------------------------------------------------------
log_vars <- c("monthly_income","savings_balance","current_balance",
              "total_outstanding_debt","debt_to_income_ratio")

cat("Skewness BEFORE log transform:\n")
for (v in log_vars) cat(sprintf("  %-25s %.2f\n", v, skew(df[[v]])))

for (v in log_vars) df[[paste0(v, "_log")]] <- log1p(df[[v]])

cat("\nSkewness AFTER log1p transform:\n")
for (v in log_vars) cat(sprintf("  %-25s %.2f\n", v, skew(df[[paste0(v,"_log")]])))

z_scale <- function(x) as.numeric(scale(x))

#' 
#' All five monetary variables were strongly right-skewed (skew up to 25.6), which would let a
#' handful of wealthy customers dominate Euclidean-distance-based clustering. Log-transforming
#' compresses the tail, and Z-scoring afterward puts all five on a comparable variance scale.
#' (`debt_to_income_ratio` and `total_outstanding_debt` retain moderate residual skew even after
#' logging -- a structural zero-inflation issue, since many customers hold no debt at all, not
#' something a transform alone fixes.)
#' 
#' ## Group B -- credit_score: robust scaling (median/IQR)
#' 
#' `credit_score` has a healthy, roughly symmetric spread with a non-zero IQR, so median/IQR
#' scaling works as intended and down-weights the small share of extreme low scores without being
#' distorted by them.
#' 
## ----preprocess-robust--------------------------------------------------------
robust_scale <- function(x) {
  med <- median(x); iqr <- IQR(x)
  (x - med) / iqr
}
cat("credit_score IQR:", IQR(df$credit_score), "\n")

#' 
#' ## Group C -- zero-inflated count variables: Min-Max normalisation
#' 
#' `num_active_loans`, `num_missed_payments`, and `overdraft_usage_yearly` are heavily
#' zero-inflated: their median AND IQR are both 0 (>=75% of customers have zero missed
#' payments/overdraft use), so median/IQR robust scaling is undefined in practice. Min-Max avoids
#' relying on a spread statistic and simply bounds each variable to [0,1].
#' 
## ----preprocess-minmax--------------------------------------------------------
minmax_vars <- c("num_active_loans","num_missed_payments","overdraft_usage_yearly")
minmax_scale <- function(x) (x - min(x)) / (max(x) - min(x))

for (v in c("num_active_loans","num_missed_payments","overdraft_usage_yearly")) {
  cat(v, " IQR:", IQR(df[[v]]), " MAD:", mad(df[[v]]), "\n")
}

#' 
#' ## Build final feature matrix
#' 
## ----build-features-----------------------------------------------------------
features <- data.frame(customer_id = df$customer_id)
for (v in log_vars) features[[paste0(v, "_z")]] <- z_scale(df[[paste0(v, "_log")]])
features[["credit_score_robust"]] <- robust_scale(df[["credit_score"]])
for (v in minmax_vars) features[[paste0(v, "_minmax")]] <- minmax_scale(df[[v]])

cat("Final feature matrix:", nrow(features), "rows x", ncol(features) - 1, "features\n")
str(features)

#' 
#' # Cluster Analysis
#' 
## ----cluster-setup------------------------------------------------------------
suppressMessages({
  library(cluster)
  library(dbscan)
  library(ggplot2)
})
X <- as.matrix(features[, -1])
set.seed(602)

#' 
#' ## K-means -- (a) Elbow method
#' 
## ----kmeans-elbow, cache=TRUE-------------------------------------------------
k_range <- 1:10
set.seed(602)
wss <- sapply(k_range, function(k) {
  km <- kmeans(X, centers = k, nstart = 10, iter.max = 50)
  km$tot.withinss
})
elbow_df <- data.frame(k = k_range, wss = wss)
elbow_df$pct_drop <- c(NA, round(100 * diff(-elbow_df$wss) / head(-elbow_df$wss, -1), 1))
print(elbow_df)

#' 
## ----elbow-plot---------------------------------------------------------------
ggplot(elbow_df, aes(k, wss)) +
  geom_line(color = "#2C6E9E", linewidth = 1) +
  geom_point(size = 2, color = "#2C6E9E") +
  geom_vline(xintercept = 6, linetype = "dashed", color = "grey40") +
  scale_x_continuous(breaks = 1:10) +
  labs(title = "K-means Elbow Method", x = "Number of clusters (k)",
       y = "Total within-cluster sum of squares (WSS)") +
  theme_minimal(base_size = 13)

#' 
#' The steep declines through k = 2-5 flatten out sharply from **k = 6 onward** -- the elbow sits
#' at k = 5 or 6.
#' 
#' ## K-means -- (b) Silhouette method
#' 
#' Computed on a random 8,000-customer sample (silhouette is O(n^2), infeasible on the full
#' 100,000 rows); cluster assignments themselves come from k-means fit on the **full** dataset.
#' 
## ----kmeans-silhouette, cache=TRUE--------------------------------------------
set.seed(602)
samp_idx <- sample(nrow(X), 8000)
Xs <- X[samp_idx, ]

sil_width <- sapply(2:10, function(k) {
  km <- kmeans(X, centers = k, nstart = 10, iter.max = 50)
  km_labels_sample <- km$cluster[samp_idx]
  ss <- silhouette(km_labels_sample, dist(Xs))
  mean(ss[, 3])
})
sil_df <- data.frame(k = 2:10, avg_silhouette = round(sil_width, 4))
print(sil_df)

#' 
## ----silhouette-plot----------------------------------------------------------
ggplot(sil_df, aes(k, avg_silhouette)) +
  geom_line(color = "#C24D2C", linewidth = 1) +
  geom_point(size = 2, color = "#C24D2C") +
  geom_vline(xintercept = 6, linetype = "dashed", color = "grey40") +
  scale_x_continuous(breaks = 2:10) +
  labs(title = "K-means Silhouette Method", x = "Number of clusters (k)",
       y = "Average silhouette width (sample n=8,000)") +
  theme_minimal(base_size = 13)

#' 
#' The global maximum is at k = 2 (0.293), but there is a clear local peak at **k = 6-7**
#' (0.286-0.288), after a dip at k = 3.
#' 
#' ## (c) Reconciling elbow vs. silhouette
#' 
#' k = 2 is statistically the tightest split but merely separates "low debt" from "high debt /
#' elevated DTI" customers -- too coarse for risk-based segmentation. **k = 6** sits at a local
#' silhouette peak nearly as high as the global maximum, and is exactly where the elbow's marginal
#' WSS gains flatten out. Profiling confirms k = 6 is business-meaningful, isolating a distinct
#' high-risk cluster. **Final choice: k = 6.**
#' 
## ----kmeans-final-------------------------------------------------------------
set.seed(602)
km6 <- kmeans(X, centers = 6, nstart = 10, iter.max = 50)
cat("Cluster sizes:\n")
print(table(km6$cluster))
cat("\nCluster centers (scaled features):\n")
print(round(km6$centers, 2))

#' 
#' ## Second clustering method: DBSCAN
#' 
#' **Why it complements K-means:** K-means assumes spherical, similarly-sized clusters and forces
#' every customer into one of k centroids -- genuine outliers get averaged into the nearest group,
#' diluting exactly the extreme-risk customers a risk-classification exercise needs to isolate.
#' DBSCAN makes no shape assumption and explicitly separates dense "normal" regions from sparse
#' outlier points, labelling the latter as **noise**.
#' 
#' `eps` was chosen from the k-distance elbow (minPts = 2 x dimensionality = 18):
#' 
## ----dbscan-eps-selection, cache=TRUE-----------------------------------------
minPts <- 2 * ncol(X)
kdist <- sort(kNNdist(X, k = minPts))
qs <- seq(0.85, 0.99, by = 0.02)
print(round(quantile(kdist, qs), 3))

#' 
## ----dbscan-final, cache=TRUE-------------------------------------------------
db <- dbscan(X, eps = 0.60, minPts = minPts)
cat("DBSCAN cluster sizes (0 = noise):\n")
print(table(db$cluster))

#' 
#' **Advantage for this data:** comparing DBSCAN's noise points against clustered points on the
#' raw (unscaled) risk variables shows the noise set is dramatically worse on every indicator
#' simultaneously -- DBSCAN surfaced this structure automatically, without being told to look for
#' "risky" customers.
#' 
## ----dbscan-profile-----------------------------------------------------------
noise_flag <- db$cluster == 0
compare_vars <- c("debt_to_income_ratio","total_outstanding_debt","num_missed_payments",
                   "overdraft_usage_yearly","credit_score","monthly_income")
for (v in compare_vars) {
  cat(sprintf("%-25s noise mean=%10.2f | clustered mean=%10.2f\n",
              v, mean(df[[v]][noise_flag]), mean(df[[v]][!noise_flag])))
}

#' 
#' ## Visual comparison (PCA projection)
#' 
## ----pca-plots, fig.width=8, fig.height=6-------------------------------------
set.seed(602)
pca <- prcomp(X, center = FALSE, scale. = FALSE)
var_exp <- round(100 * (pca$sdev^2 / sum(pca$sdev^2))[1:2], 1)

plot_df <- data.frame(PC1 = pca$x[,1], PC2 = pca$x[,2],
                        kmeans_cluster = factor(km6$cluster),
                        dbscan_cluster = factor(ifelse(db$cluster == 0, "Noise", db$cluster)))
plot_samp <- plot_df[sample(nrow(plot_df), 12000), ]

ggplot(plot_samp, aes(PC1, PC2, color = kmeans_cluster)) +
  geom_point(alpha = 0.4, size = 0.8) +
  labs(title = "K-means (k=6) clusters -- PCA projection",
       x = paste0("PC1 (", var_exp[1], "%)"), y = paste0("PC2 (", var_exp[2], "%)"),
       color = "Cluster") +
  theme_minimal(base_size = 13)

ggplot(plot_samp, aes(PC1, PC2, color = dbscan_cluster)) +
  geom_point(alpha = 0.4, size = 0.8) +
  scale_color_manual(values = c("1"="#2C6E9E","2"="#C24D2C","3"="#3A9E4D",
                                  "4"="#8E5EA2","5"="#D4A017","Noise"="grey70")) +
  labs(title = "DBSCAN clusters -- PCA projection (grey = noise/outliers)",
       x = paste0("PC1 (", var_exp[1], "%)"), y = paste0("PC2 (", var_exp[2], "%)"),
       color = "Cluster") +
  theme_minimal(base_size = 13)

#' 
#' ## Save final cluster assignments
#' 
## ----save-outputs-------------------------------------------------------------
assignments <- data.frame(
  customer_id = features$customer_id,
  kmeans_k6_cluster = km6$cluster,
  dbscan_cluster = db$cluster
)
write.csv(assignments, "final_cluster_assignments.csv", row.names = FALSE)
cat("Saved final_cluster_assignments.csv (", nrow(assignments), "rows)\n")

#' 
#' # Summary
#' 
#' - **Data generation** produced ~100,300 simulated customer records with realistic banking
#'   relationships and embedded data-quality issues.
#' - **Variable selection** focused on nine variables spanning repayment capacity, leverage, and
#'   repayment behaviour, chosen to serve a risk-segmentation business objective.
#' - **Cleaning** removed 300 exact duplicates, corrected implausible/impossible values in three
#'   variables, and median-imputed missing income and credit-score values (~10% combined).
#' - **Preprocessing** applied log1p + Z-score to skewed monetary variables, robust (median/IQR)
#'   scaling to credit score, and Min-Max scaling to zero-inflated count variables, based on
#'   empirically checked skewness and spread statistics.
#' - **K-means (k = 6)**, chosen by reconciling the elbow and silhouette diagnostics against
#'   business interpretability, produced six segments including a distinct high-risk group
#'   (~4% of customers, elevated DTI and missed payments).
#' - **DBSCAN** complemented K-means by isolating ~3.3% of customers as density-based outliers,
#'   who show sharply worse values on every raw risk indicator -- a segment K-means' centroid-based
#'   approach would otherwise average away.
